name: Build and Push Docker Image to Docker Hub

on: 
  push:
    branches: main

jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
         
      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: azadeh7049/capstone:latest
  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Update this to your desired AWS region

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name Kubernetes-capstone

      - name: Deploy to EKS
        run: |
          kubectl apply -f manifests/elasticsearch-deploy.yaml
          kubectl apply -f manifests/elasticsearch-service.yaml
