name: Build and Push Docker Image to Docker Hub

on: 
  push:
    branches: main

jobs:
  push_to_registry:
    name: push docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: check repository
        uses: actions/checkout@v2

      - name: login to docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
         
      - name: build and push docker image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: azadeh7049/capstone:latest

      - name: update kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name Kubernetes-capstone

      - name: Deploy to EKS
        run: 
          kubectl apply -f manifests/elasticsearch-deploy.yaml
          kubectl apply -f manifests/elasticsearch-service.yaml
   
