name: Build and Push Docker Image to Docker Hub

on: 
  push:
    branches: main

jobs:
  push_to_registry:
    name: push docker image to hub
    runs-on: ubuntu-latest
    steps:
      - name: check repository
        uses: actions/checkout@v2

      - name: login to docker registry
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
         
      - name: build and push docker image to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: azadeh/capstone:latest

      - name: update kubeconfig
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Deploy to EKS
        run: 
          kubectl apply -f manifests/elasticsearch-deploy.yaml
          kubectl apply -f manifests/elasticsearch-service.yaml
   
